### ISSUE TITLE
Does not generate random enough email() or username() calls. + Fork advertisement. 

### ISSUE THREAD

**Issue by polytomous** [codeneomatrix/Faker.jl#11]
Calls to 
```
Faker.email() 
```

Produce homogeneous results. Often I'll see only two email formats. This makes sense, given the way the code is written, but doesn't make sense for a random testing library. 

I know this is mostly a dead project, but if anyone is interested, a diff that can roughly resolve this issue is here: 
https://github.com/polytomous/Faker.jl/commit/b144ad595097853b5ce0b52bc652da13d2f1483c

Anyone interested on working on this project can help on my hard fork.

**Comment by codeneomatrix** [comment]
hello, thank you for your comment you are right with respect to the generation of the text I will make changes in the internal structure of the package to use sets of words in multiple languages and regarding being abandoned, it is true that I have not made updates recently I look forward to the release of version 0.7 to add those changes
