### ISSUE TITLE
Switch language to zh-CN error

### ISSUE THREAD

**Issue by huaxk** [codeneomatrix/Faker.jl#15]
`Faker.language("zh-CN")`
`ERROR: KeyError: key "university" not found`
`Stacktrace:`
` [1] getindex(::Dict{Any,Any}, ::String) at .\dict.jl:478`
` [2] language(::String) at C:\Users\hxk\.julia\packages\Faker\eecXX\src\Faker.jl:16`
` [3] top-level scope at none:0`
university key already in zh-CN.yml file, why?

**Comment by codeneomatrix** [comment]
Hi, thank you very much for notifying this error.
It is already resolved in the last commit, in the next days the version 0.2.2 will be released with this bug resolved, meanwhile you can use :

Pkg> add Faker#master

to work with this last commit

**Comment by huaxk** [comment]
Thanks for your quick response!
