### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by aminya** [codeneomatrix/Faker.jl#17]
Is package name Merly or Faker?
https://github.com/codeneomatrix/Faker.jl#installing

**Comment by codeneomatrix** [comment]
It's a mistake, the correct instruction is
Pkg> add Faker

**Comment by codeneomatrix** [comment]
thanks for the comment, I will correct it

**Comment by aminya** [comment]
Fixed by https://github.com/codeneomatrix/Faker.jl/commit/90a15ed1b071bf6f1f2028be01ce6d61b8ef4987
