### ISSUE TITLE
Conversion error on mac with Faker.date_time_ad()

### ISSUE THREAD

**Issue by abhijithch** [codeneomatrix/Faker.jl#5]
Call to the function `Faker.date_time_ad()` gives the below error on OSX. Julia version is 0.4.2.

`ERROR: MethodError: `convert` has no method matching convert(::Type{AbstractString}, ::DateTime)`

**Comment by codeneomatrix** [comment]
The problem has been corrected in the new version https://github.com/codeneomatrix/Faker.jl/releases/tag/0.0.3
Thanks for report
